### PR TITLE
Update go 1 18 3

### PR DESCRIPTION
**Pull request by to-lz1**
I updated go 1.15.6 -> 1.18.3

### CODE REVIEW

**Comment by hirosassa** [comment]
@to-lz1 I found that GitHub Actions is disabled in this repo. Is there any reason?

**Comment by to-lz1** [comment]
@hirosassa Oh, I didn't notice that. I'm sorry.

I've checked GitHub Actions configuration, but found that I can't enable them myself.

I think "Server Test" and "Client (JS) Test" should be enabled now, and we'll maintain release related jobs afterwards(this may be another PR).

image

**Comment by hirosassa** [comment]
@to-lz1 I enabled some config of GitHub Actions. Could you push some commit to run it?

**Comment by to-lz1** [comment]
@hirosassa Sorry for late reply, but I can't figure out why Github Actions still not work.

They seem work well in my forked repo. https://github.com/to-lz1/dsps/actions

Shall I change target branch from main to another new branch?

**Pull request merged**
